name: webdav
version: 1.0.9

author: timestee

description: easy webdav for dart,support basic auth,directories\files listing,upload\downliad.
homepage: https://github.com/timestee/dart-webdav

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  retry: 
  xml: 

dev_dependencies:
  pedantic: ^1.11.0
  test: '>=1.0.0 <2.0.0'
