name: dlna
description: A simple DLNA DMC library implemented by Dart. It is tiny and only the basic network video casting function is supported.
homepage: https://github.com/succlz123/DLNA-Dart
version: 0.0.5

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus:
  xml2json: 
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
