name: text_composition
description: A new Flutter package project.
version: 0.0.5
publish_to: none
author: mabdc
homepage: https://github.com/mabDc/text_composition

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/bg/
